version: "3.8"

services:
# two services || dos servicios
#1
  myjenkins:
    container_name: my_custom_jenkins
    image: jenkins/jenkins:lts  # imagen docker hub || imagen de docker hub 
    user: root
    environment:
      MY_NAME: "drdani_devops"
      # Gmail extra configuration for mailer plugin || Gmail extra configuration for mailer plugin
      JAVA_OPTS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
      SONARQUBE_HOST: mysonarqube
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Named  Docker volume details at the bottom || Detalles del volumen por defecto nombrado de Docker  con nombre en la parte inferior
      - jenkins_home:/var/jenkins_home
      # WARNING:
      - /var/run/docker.sock:/var/run/docker.sock # este volumen es peculiar ya que no es necesario si vamos a correr jenkins en una maquina externa;esto no dice que vamos a conectar socker de docker de nuestro computador con el socker de docker de nuestro contenedor; esto nos corre un dind  esto significa docker in docker.
    networks:
      - net_devops
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
#2
  mysonarqube:
    container_name: my_custom_sonarqube
    # build: ./sonarqube_home
    image: sonarqube:7.9.5-community # imagen de docker hub
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    networks:
      - net_devops
    volumes:
      - ./sonarqube_home/conf/:/opt/sonarqube/conf
      - ./sonarqube_home/data/:/opt/sonarqube/data
      - ./sonarqube_home/logs/:/opt/sonarqube/logs
      - ./sonarqube_home/extensions/:/opt/sonarqube/extensions
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3G

# To use docker-volume (custom_jenkins_home) instead of a directory path-file || Para usar docker-volume (custom_jenkins_home) en lugar de un archivo de ruta de directorio
volumes:
  jenkins_home:
    name: "custom_jenkins_home"

networks:
  net_devops:
    driver: bridge
    name: net_devops
